# LibreChat Configuration with Real Magentic-One Integration
version: 1.1.5

cache: true

endpoints:
  custom:
    - name: "Magentic-One Multi-Agent"
      apiKey: "dummy-key-not-needed"
      baseURL: "http://localhost:8090/v1"
      models:
        default: ["magentic-one"]
        fetch: false
      titleConvo: true
      titleModel: "magentic-one"
      summarize: false
      summaryModel: "magentic-one"
      forcePrompt: false
      modelDisplayLabel: "Magentic-One Agents"
      addParams:
        temperature: 0.7
        max_tokens: 2000
      dropParams: ["user"]

  openai:
    apiKey: "${OPENAI_API_KEY}"
    models:
      default: ["gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo", "gpt-4-turbo"]
      fetch: true
    titleConvo: true
    titleModel: "gpt-3.5-turbo"
    summarize: false
    summaryModel: "gpt-3.5-turbo"
    forcePrompt: false
    modelDisplayLabel: "OpenAI"

# File handling
fileStrategy: "firebase"
fileConfig:
  endpoints:
    openai:
      fileLimit: 20
      fileSizeLimit: 100
      totalSizeLimit: 1000
      supportedMimeTypes:
        - "image/png"
        - "image/jpeg"
        - "image/gif"
        - "image/webp"
        - "text/plain"
        - "application/pdf"
        - "text/csv"
        - "application/json"

# Registration and Authentication
registration:
  socialLogins: ["github", "google", "discord", "openid", "facebook"]
  allowedDomains: []

# Interface customization
interface:
  privacyPolicy:
    externalUrl: "https://librechat.ai/privacy-policy"
    openNewTab: true
  termsOfService:
    externalUrl: "https://librechat.ai/tos"
    openNewTab: true
